spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

server:
  port: ${PORT:8080}

app:
  jwt:
    expiration-ms: ${JWT_EXPIRATION_MS:3600000}