spring:
    datasource:
      url: jdbc:sqlserver://localhost:1433;databaseName=InventarioDB;encrypt=true;trustServerCertificate=true
      username: inventario_app
      password: Inventario#2026
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver